<?php /** @var stdClass $view */ ?>
<?php require('template/header.phtml') ?>

    <main class="flex-grow-1">
        <div class="container">
            <div class="p-5 mb-4 bg-light rounded-3">
                <div class="container-fluid py-5">
                    <div class="row align-items-center">
                        <div class="col-md-7">
                            <h3 class="display-5 fw-bold">Your Eyes on the Street.<br>Bringing Every Paw Home.</h3>
                            <p class="lead col-md-8 fs-4">
                                <?php
                                // Check if a user is logged in to display a personalized greeting
                                if (isset($_SESSION['username'])):
                                    ?>
                                    Welcome back, <?php echo htmlspecialchars($_SESSION['username']);?>!
                                <?php endif; ?>
                            </p>

                        </div>
                        <div class="col-md-5 text-center">
                            <img src="Images/logo.jpg" alt="PetWatch Banner" class="img-fluid shadow rounded-left">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

<?php require('template/footer.phtml') ?>