<?php /** @var stdClass $view */ ?>
<?php require('template/header.phtml'); ?>

    <main class="flex-grow-1">
        <div class="row">
            <div class="col-lg-5 col-md-6 col-sm-10 mx-auto">
                <div class="card mt-4">
                    <div class="card-body p-4">
                        <h3 class="card-title text-center mb-4">You are not Logged in</h3>
                        <div class="alert alert-success">
                            <!-- Display the message confirming successful logout -->
                            <?php echo $view->logoutMessage; ?>
                        </div>

                        <!-- Link to return to the login page -->
                        <a href="login.php" class="btn btn-outline-secondary w-100">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
<?php require('template/footer.phtml'); ?>